# Site settings
author: Conor Owens
title: 404 Cohort Not Found : A Flatiron Production
header-img: img/home-bg.png
email: conorj.owens@gmail.com
copyright_name: Conor Owens
description: > # this means to ignore newlines until "baseurl:"
  One coder's journey to get this stupid thing to work for once
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ConorOwens

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
